signature: traverse error chain, build multiline error messages
Example output with this change:
```
$ cargo update sequoia-openpgp --precise 2.1.0
$ cargo update sequoia-policy-config --precise 0.8.0
$ cargo test signature::tests::verification_helper_check
...
thread 'signature::tests::verification_helper_check' (550280) panicked at src/signature.rs:1414:14:
verify should succeed: Multiple signature errors:
Signing key on 1F5825285B785E1DB13BF36D2D11A19ABA41C6AE is not bound:
           primary key
  because: Policy rejected asymmetric algorithm
  because: EdDSA is not considered secure
Signing key on 1F5825285B785E1DB13BF36D2D11A19ABA41C6AE is not bound:
           primary key
  because: Policy rejected asymmetric algorithm
  because: EdDSA is not considered secure
...
```

While the implementation mimics the output of sequoia-sqv, and
I've referred to its error printing implementation heavily while writing this,
it ain't doing anything particularly creative here, so that should be fair use.

Resolves: #34
Signed-off-by: Alexander Sosedkin <asosedkin@redhat.com>